/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   disassemble_initialization.c                       :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: fhenrion <fhenrion@student.42.fr>          +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2020/01/09 12:14:50 by fhenrion          #+#    #+#             */
/*   Updated: 2020/01/10 20:19:35 by fhenrion         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "disassemble_initialization.h"
#include "disassemble_instructions.h"

void	disassemble_instructions_ini(t_asm_inst intruction_set[0xFF])
{
	intruction_set[0x00] = NOP;
	intruction_set[0x01] = LXI_B;
	intruction_set[0x02] = STAX_B;
	intruction_set[0x03] = INX_B;
	intruction_set[0x04] = INR_B;
	intruction_set[0x05] = DCR_B;
	intruction_set[0x06] = MVI_B;
	intruction_set[0x07] = RLC;
	intruction_set[0x08] = NOP;
	intruction_set[0x09] = DAD_B;
	intruction_set[0x0A] = LDAX_B;
	intruction_set[0x0B] = DCX_B;
	intruction_set[0x0C] = INR_C;
	intruction_set[0x0D] = DCR_C;
	intruction_set[0x0E] = MVI_C;
	intruction_set[0x0F] = RRC;
	intruction_set[0x10] = NOP;
	intruction_set[0x11] = LXI_D;
	intruction_set[0x12] = STAX_D;
	intruction_set[0x13] = INX_D;
	intruction_set[0x14] = INR_D;
	intruction_set[0x15] = DCR_D;
	intruction_set[0x16] = MVI_D;
	intruction_set[0x17] = RAL;
	intruction_set[0x18] = NOP;
	intruction_set[0x19] = DAD_D;
	intruction_set[0x1A] = LDAX_D;
	intruction_set[0x1B] = DCX_D;
	intruction_set[0x1C] = INR_E;
	intruction_set[0x1D] = DCR_E;
	intruction_set[0x1E] = MVI_E;
	intruction_set[0x1F] = RAR;
	intruction_set[0x20] = NOP;
	intruction_set[0x21] = NOP;
	intruction_set[0x22] = LXI_H;
	intruction_set[0x23] = SHLD;
	intruction_set[0x24] = INX_H;
	intruction_set[0x25] = INR_H;
	intruction_set[0x26] = DCR_H;
	intruction_set[0x27] = MVI_H;
	intruction_set[0x28] = NOP;
	intruction_set[0x29] = DAD_H;
	intruction_set[0x2A] = LHLD;
	intruction_set[0x2B] = DCX_H;
	intruction_set[0x2C] = INR_L;
	intruction_set[0x2D] = DCR_L;
	intruction_set[0x2E] = MVI_L;
	intruction_set[0x2F] = CMA;
	intruction_set[0x30] = NOP;
	intruction_set[0x31] = LXI_SP;
	intruction_set[0x32] = STA;
	intruction_set[0x33] = INX_SP;
	intruction_set[0x34] = INR_M;
	intruction_set[0x35] = DCR_M;
	intruction_set[0x36] = MVI_M;
	intruction_set[0x37] = STC;
	intruction_set[0x38] = NOP;
	intruction_set[0x39] = DAD_SP;
	intruction_set[0x3A] = LDA;
	intruction_set[0x3B] = DCX_SP;
	intruction_set[0x3C] = INR_A;
	intruction_set[0x3D] = DCR_A;
	intruction_set[0x3E] = MVI_A;
	intruction_set[0x3F] = CMC;
	intruction_set[0x40] = MOV_BB;
	intruction_set[0x41] = MOV_BC;
	intruction_set[0x42] = MOV_BD;
	intruction_set[0x43] = MOV_BE;
	intruction_set[0x44] = MOV_BH;
	intruction_set[0x45] = MOV_BL;
	intruction_set[0x46] = MOV_BM;
	intruction_set[0x47] = MOV_BA;
	intruction_set[0x48] = MOV_CB;
	intruction_set[0x49] = MOV_CC;
	intruction_set[0x4A] = MOV_CD;
	intruction_set[0x4B] = MOV_CE;
	intruction_set[0x4C] = MOV_CH;
	intruction_set[0x4D] = MOV_CL;
	intruction_set[0x4E] = MOV_CM;
	intruction_set[0x4F] = MOV_CA;
	intruction_set[0x50] = MOV_DB;
	intruction_set[0x51] = MOV_DC;
	intruction_set[0x52] = MOV_DD;
	intruction_set[0x53] = MOV_DE;
	intruction_set[0x54] = MOV_DH;
	intruction_set[0x55] = MOV_DL;
	intruction_set[0x56] = MOV_DM;
	intruction_set[0x57] = MOV_DA;
	intruction_set[0x58] = MOV_EB;
	intruction_set[0x59] = MOV_EC;
	intruction_set[0x5A] = MOV_ED;
	intruction_set[0x5B] = MOV_EE;
	intruction_set[0x5C] = MOV_EH;
	intruction_set[0x5D] = MOV_EL;
	intruction_set[0x5E] = MOV_EM;
	intruction_set[0x5F] = MOV_EA;
	intruction_set[0x60] = MOV_HB;
	intruction_set[0x61] = MOV_HC;
	intruction_set[0x62] = MOV_HD;
	intruction_set[0x63] = MOV_HE;
	intruction_set[0x64] = MOV_HH;
	intruction_set[0x65] = MOV_HL;
	intruction_set[0x66] = MOV_HM;
	intruction_set[0x67] = MOV_HA;
	intruction_set[0x68] = MOV_LB;
	intruction_set[0x69] = MOV_LC;
	intruction_set[0x6A] = MOV_LD;
	intruction_set[0x6B] = MOV_LE;
	intruction_set[0x6C] = MOV_LH;
	intruction_set[0x6D] = MOV_LL;
	intruction_set[0x6E] = MOV_LM;
	intruction_set[0x6F] = MOV_LA;
	intruction_set[0x70] = MOV_MB;
	intruction_set[0x71] = MOV_MC;
	intruction_set[0x72] = MOV_MD;
	intruction_set[0x73] = MOV_ME;
	intruction_set[0x74] = MOV_MH;
	intruction_set[0x75] = MOV_ML;
	intruction_set[0x76] = HLT;
	intruction_set[0x77] = MOV_MA;
	intruction_set[0x78] = MOV_AB;
	intruction_set[0x79] = MOV_AC;
	intruction_set[0x7A] = MOV_AD;
	intruction_set[0x7B] = MOV_AE;
	intruction_set[0x7C] = MOV_AH;
	intruction_set[0x7D] = MOV_AL;
	intruction_set[0x7E] = MOV_AM;
	intruction_set[0x7F] = MOV_AA;
	intruction_set[0x80] = ADD_B;
	intruction_set[0x81] = ADD_C;
	intruction_set[0x82] = ADD_D;
	intruction_set[0x83] = ADD_E;
	intruction_set[0x84] = ADD_H;
	intruction_set[0x85] = ADD_L;
	intruction_set[0x86] = ADD_M;
	intruction_set[0x87] = ADD_A;
	intruction_set[0x88] = ADC_B;
	intruction_set[0x89] = ADC_C;
	intruction_set[0x8A] = ADC_D;
	intruction_set[0x8B] = ADC_E;
	intruction_set[0x8C] = ADC_H;
	intruction_set[0x8D] = ADC_L;
	intruction_set[0x8E] = ADC_M;
	intruction_set[0x8F] = ADC_A;
	intruction_set[0x90] = SUB_B;
	intruction_set[0x91] = SUB_C;
	intruction_set[0x92] = SUB_D;
	intruction_set[0x93] = SUB_E;
	intruction_set[0x94] = SUB_H;
	intruction_set[0x95] = SUB_L;
	intruction_set[0x96] = SUB_M;
	intruction_set[0x97] = SUB_A;
	intruction_set[0x98] = SSB_B;
	intruction_set[0x99] = SSB_C;
	intruction_set[0x9A] = SSB_D;
	intruction_set[0x9B] = SSB_E;
	intruction_set[0x9C] = SSB_H;
	intruction_set[0x9D] = SSB_L;
	intruction_set[0x9E] = SSB_M;
	intruction_set[0x9F] = SSB_A;
	intruction_set[0xA0] = ANA_B;
	intruction_set[0xA1] = ANA_C;
	intruction_set[0xA2] = ANA_D;
	intruction_set[0xA3] = ANA_E;
	intruction_set[0xA4] = ANA_H;
	intruction_set[0xA5] = ANA_L;
	intruction_set[0xA6] = ANA_M;
	intruction_set[0xA7] = ANA_A;
	intruction_set[0xA8] = XRA_B;
	intruction_set[0xA9] = XRA_C;
	intruction_set[0xAA] = XRA_D;
	intruction_set[0xAB] = XRA_E;
	intruction_set[0xAC] = XRA_H;
	intruction_set[0xAD] = XRA_L;
	intruction_set[0xAE] = XRA_M;
	intruction_set[0xAF] = XRA_A;
	intruction_set[0xB0] = ORA_B;
	intruction_set[0xB1] = ORA_C;
	intruction_set[0xB2] = ORA_D;
	intruction_set[0xB3] = ORA_E;
	intruction_set[0xB4] = ORA_H;
	intruction_set[0xB5] = ORA_L;
	intruction_set[0xB6] = ORA_M;
	intruction_set[0xB7] = ORA_A;
	intruction_set[0xB8] = CMP_B;
	intruction_set[0xB9] = CMP_C;
	intruction_set[0xBA] = CMP_D;
	intruction_set[0xBB] = CMP_E;
	intruction_set[0xBC] = CMP_H;
	intruction_set[0xBD] = CMP_L;
	intruction_set[0xBE] = CMP_M;
	intruction_set[0xBF] = CMP_A;
	intruction_set[0xC0] = RNZ;
	intruction_set[0xC1] = POP_B;
	intruction_set[0xC2] = JNZ;
	intruction_set[0xC3] = JMP;
	intruction_set[0xC4] = CNZ;
	intruction_set[0xC5] = PUSH_B;
	intruction_set[0xC6] = ADI;
	intruction_set[0xC7] = RST_0;
	intruction_set[0xC8] = RZ;
	intruction_set[0xC9] = RET;
	intruction_set[0xCA] = JZ;
	intruction_set[0xCB] = JMP;
	intruction_set[0xCC] = CZ;
	intruction_set[0xCD] = CALL;
	intruction_set[0xCE] = ACI;
	intruction_set[0xCF] = RST_1;
	/*
	0xc0: printf("RNZ");
	0xc1: printf("POP    B");
	0xc2: printf("JNZ    $%02x%02x",code[2],code[1]); opbytes = 3;
	0xc3: printf("JMP    $%02x%02x",code[2],code[1]); opbytes = 3;
	0xc4: printf("CNZ    $%02x%02x",code[2],code[1]); opbytes = 3;
	0xc5: printf("PUSH   B");
	0xc6: printf("ADI    #$%02x",code[1]); opbytes = 2;
	0xc7: printf("RST    0");
	0xc8: printf("RZ");
	0xc9: printf("RET");
	0xca: printf("JZ     $%02x%02x",code[2],code[1]); opbytes = 3;
	0xcb: printf("JMP    $%02x%02x",code[2],code[1]); opbytes = 3;
	0xcc: printf("CZ     $%02x%02x",code[2],code[1]); opbytes = 3;
	0xcd: printf("CALL   $%02x%02x",code[2],code[1]); opbytes = 3;
	0xce: printf("ACI    #$%02x",code[1]); opbytes = 2;
	0xcf: printf("RST    1");
	0xd0: printf("RNC");
	0xd1: printf("POP    D");
	0xd2: printf("JNC    $%02x%02x",code[2],code[1]); opbytes = 3;
	0xd3: printf("OUT    #$%02x",code[1]); opbytes = 2;
	0xd4: printf("CNC    $%02x%02x",code[2],code[1]); opbytes = 3;
	0xd5: printf("PUSH   D");
	0xd6: printf("SUI    #$%02x",code[1]); opbytes = 2;
	0xd7: printf("RST    2");
	0xd8: printf("RC"); 
	0xd9: printf("RET");
	0xda: printf("JC     $%02x%02x",code[2],code[1]); opbytes = 3;
	0xdb: printf("IN     #$%02x",code[1]); opbytes = 2;
	0xdc: printf("CC     $%02x%02x",code[2],code[1]); opbytes = 3;
	0xdd: printf("CALL   $%02x%02x",code[2],code[1]); opbytes = 3;
	0xde: printf("SBI    #$%02x",code[1]); opbytes = 2;
	0xdf: printf("RST    3");
	0xe0: printf("RPO");
	0xe1: printf("POP    H");
	0xe2: printf("JPO    $%02x%02x",code[2],code[1]); opbytes = 3;
	0xe3: printf("XTHL");break;
	0xe4: printf("CPO    $%02x%02x",code[2],code[1]); opbytes = 3;
	0xe5: printf("PUSH   H");
	0xe6: printf("ANI    #$%02x",code[1]); opbytes = 2;
	0xe7: printf("RST    4");
	0xe8: printf("RPE");
	0xe9: printf("PCHL");break;
	0xea: printf("JPE    $%02x%02x",code[2],code[1]); opbytes = 3;
	0xeb: printf("XCHG");
	0xec: printf("CPE     $%02x%02x",code[2],code[1]); opbytes = 3;
	0xed: printf("CALL   $%02x%02x",code[2],code[1]); opbytes = 3;
	0xee: printf("XRI    #$%02x",code[1]); opbytes = 2;
	0xef: printf("RST    5");
	0xf0: printf("RP"); 
	0xf1: printf("POP    PSW");
	0xf2: printf("JP     $%02x%02x",code[2],code[1]); opbytes = 3;
	0xf3: printf("DI"); 
	0xf4: printf("CP     $%02x%02x",code[2],code[1]); opbytes = 3;
	0xf5: printf("PUSH   PSW");
	0xf6: printf("ORI    #$%02x",code[1]); opbytes = 2;
	0xf7: printf("RST    6");
	0xf8: printf("RM"); 
	0xf9: printf("SPHL");break;
	0xfa: printf("JM     $%02x%02x",code[2],code[1]); opbytes = 3;
	0xfb: printf("EI"); 
	0xfc: printf("CM     $%02x%02x",code[2],code[1]); opbytes = 3;
	0xfd: printf("CALL   $%02x%02x",code[2],code[1]); opbytes = 3;
	0xfe: printf("CPI    #$%02x",code[1]); opbytes = 2;
	0xff: printf("RST    7");
	*/
	// to continue
	intruction_set[0xC3] = JMP;
}
